# Generated by Django 2.0.5 on 2018-05-16 10:10

import daemon.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pic', models.ImageField(upload_to=daemon.models.scramble_uploaded_filename, verbose_name='Uploaded image')),
                ('original_filename', models.TextField(default='', verbose_name='Original filename')),
                ('description', models.TextField(default='', verbose_name='Description of the uploaded image')),
            ],
        ),
        migrations.CreateModel(
            name='WebpageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=2083, validators=[django.core.validators.URLValidator])),
                ('crontab', models.CharField(max_length=50, validators=[daemon.models.validate_crontab])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='daemon.WebpageOrder'),
        ),
    ]
