# Generated by Django 2.0.5 on 2018-05-11 14:23

import daemon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.TextField(default='', verbose_name='Description of the uploaded image'),
        ),
        migrations.AddField(
            model_name='picture',
            name='original_filename',
            field=models.TextField(default='', verbose_name='Original filename'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to=daemon.models.scramble_uploaded_filename, verbose_name='Uploaded image'),
        ),
    ]
