# Generated by Django 2.0.5 on 2018-05-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpageorder',
            name='crontab',
            field=models.CharField(default='* * * * *', max_length=30),
            preserve_default=False,
        ),
    ]
