# Generated by Django 2.0.5 on 2018-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_webpageorder_crontab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpageorder',
            name='crontab',
            field=models.CharField(max_length=50),
        ),
    ]
